### ISSUE TITLE
MEI-Friend does not load on Mac - Uncaught TypeError: Cannot read property 'setTabLength' of undefined

### ISSUE THREAD

**Issue by apacha** [trompamusic/mei-friend#8]
I'm trying to get the MEI-Friend to work, but on my MacBook I can't get the rendering (on Windows it worked fine). I've tried re-installing, restarting, reloading, but nothing seems to work. Toggling MEI-Friend doesn't do anything, similarly to the menu-options. Did the plug-in maybe crash upon loading? I'm sometimes getting the following error when opening a file, but I'm not sure if it is related to it.

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.2.3
**Thrown From**: [mei-friend](https://github.com/trompamusic/mei-friend) package 0.3.5

### Stack Trace

Uncaught TypeError: Cannot read property 'setTabLength' of undefined

```
At /Users/alex/.atom/packages/mei-friend/lib/mei-friend.js:45

TypeError: Cannot read property 'setTabLength' of undefined
    at /packages/mei-friend/lib/mei-friend.js:45:25
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1191622)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:425974)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:44778
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1191622)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:448083)
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:447560)
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:464978)
    at Pane.focus (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:456421)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
```

### Non-Core Packages

```
language-mei 0.34.5 
mei-friend 0.3.5 
```

**Comment by wergo** [comment]
Thanks for pointing to this, @apacha. I had once this error (on a Windows machine), but I cannot reproduce it (I am testing on Mac). I have secured this line so that `setTabLength` is not read when `undefined` (in 0.3.6).

**Comment by apacha** [comment]
Thanks for the quick fix. I guess, I have to setup some debugging on my own, to be able to provide you with more insights. I've updated to 0.3.6 and I'm getting this now:

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.2.3
**Thrown From**: [mei-friend](https://github.com/trompamusic/mei-friend) package 0.3.6


### Stack Trace

Uncaught TypeError: item.setTabLength is not a function

```
At /Users/alex/.atom/packages/mei-friend/lib/mei-friend-view.js:62

TypeError: item.setTabLength is not a function
    at /packages/mei-friend/lib/mei-friend-view.js:62:12
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1191622)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:448083)
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:447560)
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:464978)
    at Pane.focus (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:456421)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Non-Core Packages

```
language-mei 0.34.5 
mei-friend 0.3.6 
`
``

Can you link me to some resources, how I can start debugging the MEI-Friend?

**Comment by wergo** [comment]
Thanks & merde. Shall we briefly speak on Slack or Zoom?

**Comment by wergo** [comment]
Great that it is solved now. It must have something to do with reloading the window (rather than any specific MEI-friend things).
